import { GroupSettings, TimelineCreateDate } from '../../domain/api-types.js';
import { ConnectorId } from '../../domain/connector.js';
import { Scope } from '../../domain/context.js';
import { ContextItemsFiltersWithOperator } from '../../domain/filters.js';
import { HierarchyType } from '../../domain/hierarchy.js';
import { Timeline } from '../../domain/timeline.js';
import { EngineRuntime } from '../../ports/runtime.js';
import { ActivityItemGraph } from '../activity-graph.js';
import { VisualizationResult } from './visualization.js';

/**
 * Supported parameter types for insight configuration.
 * Each type maps to a specific UI control on the frontend.
 */
export enum InsightParameterType {
    /** Numeric input (integer or float) */
    Number = 'number',
    /** Free-form text input */
    Text = 'text',
    /** Boolean toggle */
    Boolean = 'boolean',
    /** Single selection from a list of options */
    Select = 'select',
}

/**
 * Declaration of a single configurable parameter for an insight.
 * Lives on InsightConfig alongside the insight definition.
 */
export interface InsightParameterDeclaration {
    /** Unique key for this parameter within the insight (used as the JSON key in stored values) */
    key: string;
    /** Human-readable label shown in the UI */
    label: string;
    /** Type of the parameter, determines the UI control rendered */
    type: InsightParameterType;
    /** Default value used when no user value is provided */
    defaultValue: number | boolean | string;
    /** Optional description/help text shown in the UI */
    description?: string;
    /** Validation constraints (type-specific) */
    constraints?: {
        /** For Number: minimum allowed value */
        min?: number;
        /** For Number: maximum allowed value */
        max?: number;
        /** For Number: step increment */
        step?: number;
        /** For Select: list of allowed options with labels */
        options?: { value: string; label: string }[];
    };
}

/** Resolved insight parameter values with defaults applied */
export type ResolvedInsightParameters = Record<string, number | boolean | string>;

/**
 * A delta period specifying an explicit date range for comparison
 */
export interface DeltaPeriod {
    fromDate: Date;
    toDate: Date;
}

/**
 * Insight results as text, cached for LLM/chat consumption
 * (formerly `GraphAnalyticsLLMContext`).
 */
export interface InsightLlmContext {
    /** ID of the analysis run */
    id: string;
    /** Organization ID for org-level permissions */
    organizationId?: string;
    /** Config-specific analyzed data as text */
    analysesText: string;
    /** Generic graph representation as text */
    graphTexts: { name: string | undefined; text: string }[];
    permissions: InsightLlmContextPermissions;
}

export interface InsightLlmContextPermissions {
    /** Users allowed to read this context. */
    viewUserIds: string[];
    /** Whether anyone in the same organization may read this context. */
    orgView: boolean;
}

/**
 * Context provided to analysis function and config functions
 */
export interface AnalysisContext {
    userId: string;
    organizationId: string;
    userIanaZone: string;
    scopes: Scope[];

    /** Full unfiltered timeline */
    timeline: Timeline;

    /** Start date for this analysis period */
    fromDate: Date;

    /** Optional end date for this analysis period */
    toDate?: Date;

    /** True when this run is a delta/comparison analysis (deltaPeriods is non-empty) */
    isDeltaAnalysis: boolean;

    /** Engine runtime for accessing services (logger, cache, repositories, LLM) */
    runtime: EngineRuntime;

    /** Delta periods for comparison, each specifying an explicit date range */
    deltaPeriods?: DeltaPeriod[];

    /**
     * Optional filters from data sources.
     * When provided, these are merged with the insight's own filters.
     */
    dataSourceFilters?: ContextItemsFiltersWithOperator;

    /** Metadata when using `fetchTimeline` */
    timelineMetadata?: Record<string, unknown>;

    /** Stable cache key generated by the caller for the session */
    cacheSessionKey: string;

    /** Resolved parameter values for this insight instance, with defaults applied */
    insightParameters: ResolvedInsightParameters;
}

/**
 * Parameters provided to analysis execution
 */
export interface AnalysisParams {
    userId: string;
    organizationId: string;
    timeline: Timeline;
    timelineId: string;
    scopes: Scope[];
    fromDate: Date;
    toDate?: Date;
    userIanaZone: string;
    runtime: EngineRuntime;

    /** Delta periods with explicit date ranges. If provided, runs delta analysis */
    deltaPeriods?: DeltaPeriod[];

    /**
     * Optional filters from data sources.
     * When provided, these are merged with the insight's own filters.
     */
    dataSourceFilters?: ContextItemsFiltersWithOperator;

    /** Enable caching of analysis text for LLM queries */
    cache?: {
        permissions: InsightLlmContextPermissions;
        ttl?: number;
    };

    /** Metadata when using `fetchTimeline` */
    timelineMetadata?: Record<string, unknown>;

    /** Stable cache key generated by the caller for the session */
    cacheSessionKey: string;

    /** Resolved parameter values for this insight instance, with defaults applied */
    insightParameters: ResolvedInsightParameters;
}

/**
 * Result from a single analysis run
 */
export interface AnalysisResult {
    /** The period this analysis covers */
    period: {
        fromDate: Date;
        toDate?: Date;
    };

    /** Flexible storage for analysis data */
    aggregations: Map<string, unknown>;

    /** Key metrics as distributions (used for delta calculations) */
    distributions: Record<string, number>;

    /** Additional metadata */
    metadata?: Record<string, unknown>;
}

/**
 * Graphs to be analyzed in a single run
 */
export interface AnalysedGraphs {
    /** The main graph, per the primary grouping option */
    mainGraph: {
        name?: string | undefined;
        graph: ActivityItemGraph;
    };
    /** Sub-graphs, per the secondary grouping option (if any) */
    subGraphs: {
        name: string;
        graph: ActivityItemGraph;
    }[];
}

/**
 * Analysis result with optional delta comparisons
 */
export interface AnalysisResultWithDeltas {
    /**
     * Deterministic ID for this analysis run
     * Format: {configId}:{userId}:{timelineId}:{filterHash}
     */
    analysisId: string;

    /** Current period analysis */
    current: AnalysisResult;

    /** Delta period analyses with calculated changes */
    deltas?: Array<{
        /** The date range for this delta period */
        period: DeltaPeriod;

        /** Analysis result for the previous period */
        analysis: AnalysisResult;

        /** Calculated changes between current and previous */
        changes: {
            absolute: Record<string, number>;
            percentage: Record<string, number>;
        };
    }>;
}

export interface FetchTimelineResult {
    timeline: Timeline;
    timelineId: string;
    fromDate: Date;
    metadata: Record<string, unknown> | undefined;
}

/**
 * Configuration for an insight (formerly `GraphAnalyticsConfig`)
 */
export interface InsightConfig {
    /** identifier for this insight type */
    id: string;

    /** Display name */
    name: string;

    /** Which connectors and contexts this applies to */
    applicability: {
        connectors?: ConnectorId[];
        hierarchyTypes?: HierarchyType[];
    };

    /** Disable delta analysis for this insight type */
    disableDeltaAnalysis?: boolean;

    /** Whether to return an empty timeline if there are not changes or null - default is to return null to avoid unnecessary analysis runs */
    allowEmptyTimeline?: boolean;

    /**
     * Optional parameter declarations for this insight.
     * When present, a frontend can render configuration controls
     * and values will be stored per-insight-instance.
     */
    parameters?: InsightParameterDeclaration[];

    /**
     * Optional hook to provide custom timeline construction.
     * When implemented, this is called instead of the engine's cached timeline builder.
     * The returned timeline and fromDate are used for all subsequent operations.
     *
     * Use cases:
     * - Insights that need a different date range than the user-provided fromDate
     * - Insights that need to pre-fetch custom data
     */
    fetchTimeline?: (params: {
        userId: string;
        organizationId: string;
        scopes: Scope[];
        fromDate: TimelineCreateDate;
        toDate?: TimelineCreateDate;
        userIanaZone: string;
        cacheSessionKey: string;
        runtime: EngineRuntime;
        /** Resolved parameter values with defaults applied */
        insightParameters: ResolvedInsightParameters;
    }) => Promise<FetchTimelineResult | undefined>;

    /** How to group items for analysis - can vary based on context */
    getGrouping: (context: AnalysisContext) => { primary: GroupSettings; secondary?: GroupSettings };

    /** Filters to apply - can vary based on context (handles date logic per implementation) */
    getFilters: (context: AnalysisContext) => ContextItemsFiltersWithOperator;

    /** Analysis function - called once per period (current + each delta) */
    analyze: (graphs: AnalysedGraphs[], context: AnalysisContext) => Promise<AnalysisResult>;

    /** Format function - receives all results and returns formatted insight. `analysisWithDeltas` can be undefined when there is no data found */
    formatResult: (
        analysisWithDeltas: AnalysisResultWithDeltas | undefined,
        context: AnalysisContext,
    ) => VisualizationResult;

    /**
     * Convert analyzed data into text for LLM context
     * Called after analyze() if caching is enabled
     */
    getAnalyzedDataAsText: (
        analysisWithDeltas: AnalysisResultWithDeltas,
        context: AnalysisContext,
    ) => Promise<string> | string;
}

/**
 * Resolve user-provided parameter values against the insight's declarations.
 * Applies defaults for missing values and validates/coerces types.
 */
export function resolveInsightParameters(
    declarations: InsightParameterDeclaration[] | undefined,
    userValues: Record<string, unknown> | undefined,
): ResolvedInsightParameters {
    const resolved: ResolvedInsightParameters = {};
    if (!declarations || declarations.length === 0) {
        return resolved;
    }

    for (const decl of declarations) {
        const userVal = userValues?.[decl.key];
        if (userVal !== undefined && userVal !== null) {
            resolved[decl.key] = coerceParameterValue(decl, userVal);
        } else {
            resolved[decl.key] = decl.defaultValue;
        }
    }
    return resolved;
}

function coerceParameterValue(decl: InsightParameterDeclaration, value: unknown): number | boolean | string {
    switch (decl.type) {
        case InsightParameterType.Number: {
            const num = typeof value === 'number' ? value : Number(value);
            if (isNaN(num)) {
                return decl.defaultValue;
            }
            const clamped =
                decl.constraints?.min !== undefined || decl.constraints?.max !== undefined
                    ? Math.min(Math.max(num, decl.constraints?.min ?? -Infinity), decl.constraints?.max ?? Infinity)
                    : num;
            return clamped;
        }
        case InsightParameterType.Boolean: {
            if (typeof value === 'boolean') {
                return value;
            }
            if (value === 'true') return true;
            if (value === 'false') return false;
            return decl.defaultValue;
        }
        case InsightParameterType.Text: {
            return String(value);
        }
        case InsightParameterType.Select: {
            const strVal = String(value);
            const validOptions = decl.constraints?.options?.map((o) => o.value);
            if (validOptions && !validOptions.includes(strVal)) {
                return decl.defaultValue;
            }
            return strVal;
        }
        default:
            return decl.defaultValue;
    }
}
